# Generated by Django 6.0.3 on 2026-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_benches_per_row_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seating',
            unique_together={('exam', 'room', 'row', 'seat_position'), ('exam', 'student')},
        ),
        migrations.AlterField(
            model_name='seating',
            name='seat_position',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='seating',
            name='bench',
        ),
    ]
