# Generated by Django 6.0.3 on 2026-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_semester_options_student_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
