# Generated by Django 6.0.3 on 2026-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_systemsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sem_type',
            field=models.CharField(blank=True, choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['sem_type'], name='api_student_sem_typ_bee8f7_idx'),
        ),
    ]
