# Generated by Django 4.2.10 on 2026-04-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_sem_student_sem_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
                ('sem_type', models.CharField(choices=[('ODD', 'ODD'), ('EVEN', 'EVEN')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='api_exam_date_ee9322_idx',
        ),
        migrations.RemoveIndex(
            model_name='seating',
            name='api_seating_student_aab49d_idx',
        ),
        migrations.RemoveIndex(
            model_name='seating',
            name='api_seating_room_id_3d54d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='seating',
            name='api_seating_exam_id_f5c396_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='api_student_departm_0cf16a_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='api_student_semeste_4afa34_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='api_student_sem_typ_bee8f7_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='department',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university_id',
        ),
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.program'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.program'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['sem_type'], name='api_enrollm_sem_typ_5d89a8_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['semester'], name='api_enrollm_semeste_dedfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section'], name='api_enrollm_section_f55b35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'program', 'semester')},
        ),
    ]
