# Generated by Django 4.2.5 on 2026-04-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enrollment_unique_constraint_and_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='enrollment_semester_sem_type_match',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='api_enrollm_program_8bf0f0_idx',
            old_name='api_enrollm_program_d5793e_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='api_enrollm_program_9a1302_idx',
            old_name='api_enrollm_program_2ed346_idx',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sem_type', 'ODD'), ('semester__in', (1, 3, 5))), models.Q(('sem_type', 'EVEN'), ('semester__in', (2, 4, 6))), _connector='OR'), name='enrollment_semester_sem_type_match'),
        ),
    ]
