# Generated by Codex on 2026-04-19

from django.db import migrations, models
import django.db.models.deletion


def backfill_exam_programs(apps, schema_editor):
    Exam = apps.get_model('api', 'Exam')
    Program = apps.get_model('api', 'Program')

    default_program = Program.objects.order_by('id').first()
    if default_program is None:
        default_program, _ = Program.objects.get_or_create(name='UNASSIGNED')

    Exam.objects.filter(program__isnull=True).update(program=default_program)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_enrollment_enrollment_semester_sem_type_match_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_exam_programs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='exam',
            name='program',
            field=models.ForeignKey(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='exams',
                to='api.program',
            ),
        ),
    ]
