# Generated by Django 4.2.5 on 2026-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_exam_exam_type_alter_exam_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='aisle_after_column',
            field=models.JSONField(blank=True, default=list, help_text='Block indices after which to place an aisle'),
        ),
        migrations.AddField(
            model_name='room',
            name='column_layout',
            field=models.JSONField(default=list, help_text='List of seat counts per block, e.g. [3, 2, 3]'),
        ),
    ]
