# Generated by Django 4.2.5 on 2026-04-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_room_aisle_after_column_room_column_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='DRAFT', max_length=20)),
                ('constraint_level_used', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='api.exam')),
            ],
            options={
                'verbose_name': 'Seating Plan',
                'verbose_name_plural': 'Seating Plans',
                'ordering': ['-version'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='seating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seating',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.seatingplan'),
        ),
        migrations.AlterUniqueTogether(
            name='seating',
            unique_together={('plan', 'room', 'row', 'seat_position'), ('plan', 'student')},
        ),
    ]
