# Generated by Django 4.2.5 on 2026-07-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_seatingplan_alter_seating_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Regular'), ('SUPPLEMENTARY', 'Supplementary'), ('INTERNAL', 'Internal Assessment'), ('PRACTICAL', 'Practical')], default='REGULAR', max_length=20)),
                ('exam_date', models.DateField()),
                ('session', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='MORNING', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('COMMON', 'Common')], default='CORE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.program')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='program',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='seating',
            name='exam_group',
        ),
        migrations.RemoveField(
            model_name='seatingplan',
            name='exam',
        ),
        migrations.AlterField(
            model_name='seatingplan',
            name='constraint_level_used',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ExamGroup',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='api.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='exam_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.examschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seating',
            name='exam_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.examschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='exam_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='api.examschedule'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('exam_schedule', 'room')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='exam',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
