# Generated by Django 6.0.3 on 2026-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='benches_per_row',
        ),
        migrations.RemoveField(
            model_name='room',
            name='students_per_bench',
        ),
        migrations.AddField(
            model_name='room',
            name='left_seats',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='middle_seats',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='right_seats',
            field=models.IntegerField(default=3),
        ),
    ]
