# Generated by Django 6.0.3 on 2026-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_seating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
