# Generated by Django 6.0.3 on 2026-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sem_type', models.CharField(choices=[('ODD', 'ODD Semester (1, 3, 5)'), ('EVEN', 'EVEN Semester (2, 4, 6)')], default='ODD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'subject'], name='api_exam_date_ee9322_idx'),
        ),
        migrations.AddIndex(
            model_name='seating',
            index=models.Index(fields=['student'], name='api_seating_student_aab49d_idx'),
        ),
        migrations.AddIndex(
            model_name='seating',
            index=models.Index(fields=['room'], name='api_seating_room_id_3d54d2_idx'),
        ),
        migrations.AddIndex(
            model_name='seating',
            index=models.Index(fields=['exam'], name='api_seating_exam_id_f5c396_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='api_student_departm_0cf16a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester'], name='api_student_semeste_4afa34_idx'),
        ),
    ]
