# Generated by Django 6.0.3 on 2026-04-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_sem_student_sem_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='api_student_sem_typ_bee8f7_idx',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sem_type',
        ),
    ]
