# Generated by Django 4.2.5 on 2026-04-19 16:23

from django.db import migrations, models
import django.db.models.deletion


def backfill_exam_groups(apps, schema_editor):
    Exam = apps.get_model('api', 'Exam')
    ExamGroup = apps.get_model('api', 'ExamGroup')
    Seating = apps.get_model('api', 'Seating')

    for exam in Exam.objects.all().iterator():
        if exam.program_id is None or exam.semester is None:
            continue

        exam_group, _ = ExamGroup.objects.get_or_create(
            exam_id=exam.id,
            program_id=exam.program_id,
            semester=exam.semester,
            subject=str(exam.subject or '').upper().strip(),
        )
        Seating.objects.filter(exam_id=exam.id, exam_group__isnull=True).update(exam_group_id=exam_group.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_backfill_exam_programs_and_make_program_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('COMMON', 'Common Subject'), ('CORE', 'Department Specific')], default='CORE', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.program'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.exam')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_groups', to='api.program')),
            ],
        ),
        migrations.AddField(
            model_name='seating',
            name='exam_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.examgroup'),
        ),
        migrations.AddIndex(
            model_name='examgroup',
            index=models.Index(fields=['exam', 'program', 'semester'], name='api_examgro_exam_id_3c760f_idx'),
        ),
        migrations.AddIndex(
            model_name='examgroup',
            index=models.Index(fields=['subject'], name='api_examgro_subject_73146e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examgroup',
            unique_together={('exam', 'program', 'semester', 'subject')},
        ),
        migrations.RunPython(backfill_exam_groups, noop_reverse),
    ]
